name: cravex
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.6
  cupertino_icons: ^1.0.8
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.17.0
  url_launcher: ^6.1.10
  http: ^1.2.0
  flutter_stripe: ^12.1.1
  image_picker: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/Poppins/Poppins-Italic.ttf
          style: italic

  assets:
    - assets/Images/
